apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec: 
  selector:
    matchLabels: 
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: florinpana01/tradetreasure-user-service-repository
          ports:
            - containerPort: 8000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-service-db-secret
                  key: username
            - name: DB_PASS
              valueFrom: 
                secretKeyRef:
                  name: user-service-db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: user-service-db-secret
                  key: database
